### ISSUE TITLE
filtered word not displayed to admins

### ISSUE THREAD

**Issue by DevSHIBBY** [AresChat/sb0t#11]
Hi,

I've applied many word filters to keep disruptive users away from my room but sometime other users get filtered for some reason, and I can't see any option or setting that would allow moderators or me (the host) to see what the filter blocked. If my memory serves me right, the Ares chat server does this, so could it be done too by sb0t?

**Comment by thispixel** [comment]
What type of filter is it? Ie ban, muzzle etc

**Comment by DevSHIBBY** [comment]
mostly kick & ban

**Comment by thispixel** [comment]
I'll add the filtered word to the log

**Comment by DevSHIBBY** [comment]
Could it be displayed live for moderators & owner on the main screen too?

**Comment by thispixel** [comment]
could possibly be obtrusive, i'll see what I can do.

**Comment by DevSHIBBY** [comment]
Ok, thanks a lot for the fast replies!
