### ISSUE TITLE
Joinfilters

### ISSUE THREAD

**Issue by Cobreti1** [AresChat/sb0t#12]
Hello stuart, I hope you can drag the input filters #joinfilter, they do not work and use vpn, it's a mockery for host nothing stops them. I hope someday just leave the rooms in room list, can not take the ip, those who are believed to be hackers every day to knock out rooms is the bread of every day, greetings :(

**Comment by hollow87** [comment]
Is there a specific issue with the join filters? Can you give more information on the issue with them?

**Comment by Cobreti1** [comment]
hi hollow i am cobra. In specific filters are filter join, does not work do not reject filtering example: nameban, ip and portban .. greetings

**Comment by hollow87** [comment]
Nameban doesn't work? Can you give me an example of the nameban filter used and the user bypasses it?

**Comment by Cobreti1** [comment]
hi dude, ejem: - VEERGATRONZ [NameBan]    <-- dont work

**Comment by hollow87** [comment]
Would a name ban that compares anywhere in the name instead of exact match fix the issue with nameban?

**Comment by Cobreti1** [comment]
hey hollow 
The problem is not working filter joinfilter. ok good night

**Comment by Nemo2478** [comment]
hollow87,

where can i post programming questions?

**Comment by Nemo2478** [comment]
pleasehelp me

**Comment by ohgoshdean** [comment]
Nemo,

Programming questions regarding cb0t/sb0t - there is no where for such questions. Github issues are ONLY for issues with the applications (ie. bugs).

For general programming questions, there are a number of online communities (ie. stackoverflow.com<http://stackoverflow.com/>).
