### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#13]
Hello,

I am watching the source code from Sb0t 5.36 and I wanted to know where are the part, who the user are disconnected by ban.

Bye and thanks

**Comment by hollow87** [comment]
Are you talking about the blacklist? If so that has been removed.

**Comment by Nemo2478** [comment]
Hello hollow87,

No. I am talking about the part about the Disconnection from a user by a ban.

**Comment by hollow87** [comment]
Can you give more details on the bug? Testing here bans work.

**Comment by Nemo2478** [comment]
Hello,

I dont mean a bug. I mean following:

Please open the project. Than go to commands > Evals.cs > Line 86
As we see target.Ban(); go to iconnect > IUser.cs > Linea 122
And than? All ends here? Where is the process of desconection by a ban?

**Comment by ohgoshdean** [comment]
Nemo2478,

Check AresClient.cs. :)

Sent from my iPhone

On 14 Feb 2017, at 16:16, Nemo2478 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I dont mean a bug. I mean following:

Please open the project. Than go to commands > Evals.cs > Line 86
As we see target.Ban(); go to iconnect > IUser.cs > Linea 122
And than? All ends here? Where is the process of desconection by a ban?

**Comment by hollow87** [comment]
Ban Method in core/AresClient.cs as @ohgoshdean commented.

Issue Closed
