### ISSUE TITLE
Flag

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#14]
Hello,

I checked the source code from Cb0t and I have a question in this part:
Scripting > Static > JSEvents.cs > Line 75:

        [JSFunction(Name = "onconnected", Flags = JSFunctionFlags.HasEngineParameter, IsWritable = false, IsEnumerable = true)]

What is meaned with Flags?

Bye and Thanks

**Comment by hollow87** [comment]
Flags is an argument to the JS engine look at Jurassic documentation.
Please use this to report issues not asking general programming questions.
