### ISSUE TITLE
Scripts 

### ISSUE THREAD

**Issue by Cobreti1** [AresChat/sb0t#15]
Hi stuart new problem, through script done sorrow programmers etc, they found back door in the scripts, they already get to be host

**Comment by hollow87** [comment]
Is it a script provided by livescripts? If so what is the script name

**Comment by Cobreti1** [comment]
yes script call multi.js by sorrow

**Comment by Cobreti1** [comment]
dont provided by livescripts.

**Comment by hollow87** [comment]
Talk to the author of the script.  Unless it is a bug with the scripting engine or one of the scripts on live scripts. This issue is closed
