### ISSUE TITLE
Linked admin don't always work across rooms

### ISSUE THREAD

**Issue by Tekwizz** [AresChat/sb0t#17]
Not sure about two rooms linked, but when three are linked, admin actions don't work reliably across them.

**Comment by hollow87** [comment]
Do you know exactly which admin actions do not work across linked rooms?

**Comment by Tekwizz** [comment]
Ban, kill, muzzle, disableavatar, I guess all of them, sometimes they work... It's inconsistent.

**Comment by hollow87** [comment]
Briefly looking, it does look like it's not implemented at all to propagate admin commands.

**Comment by Tekwizz** [comment]
The funny thing is that sometimes it does work! Once it didn't work so I restarted the bots and then it did work again.. There must be some error somewhere...

**Comment by Cobreti1** [comment]
hey tekwizz, just restart your sbot, now allow link work,
