### ISSUE TITLE
Upload complete project

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#23]
Hello,
could you, the next time, upload the complete project and not only the library class?

Its very dificult for me convert the .exe in a project.

Bye and thanks

**Comment by hollow87** [comment]
This is the complete project you just have to build the solution.

**Comment by Nemo2478** [comment]
When I try to build the solution Visual Studio says, that he needs an .exe. In the project are not an .exe.

**Comment by hollow87** [comment]
Yes there is, the project "gui" is the ".exe" you are looking for.  In your case you are trying to Run/Debug one of the supoorting class libraries rather than just build the solution.  I recommend learning more about your Visual Studio in general rather than claiming part of the project is missing.

**Comment by Nemo2478** [comment]
1) Although the project "gui" is the ".exe" i cant see the design, the controls. Its no my guilt when you make the solution more dificult that he alredy is.

2) How can in the scripting of Sb0t write scripts in a new line?

Bye and thanks

**Comment by hollow87** [comment]
The main window for the gui resides here 

https://github.com/AresChat/sb0t/blob/2b0c165/gui/MainWindow.xaml

It is a standard xaml file we didn't do anything special to make it more difficult.

Issue is closed as the original question was answered
