### ISSUE TITLE
Password-Query

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#26]
Hello hollow,

ist possible to send to a server a password-Query? 
Who?

Bye and Thanks

**Comment by hollow87** [comment]
Not sure what you mean. Please provide more information in better English.

**Comment by Nemo2478** [comment]
I am admin in a server.
And I want to send a Query to any server.
See this so you understand better: http://wiki.sa-mp.com/wiki/Query_Mechanism/Csharp

In this example you can see how to send a password-Query to a server. So you compare a password.

Is this possible with Sb0t?

Bye and thanks

**Comment by hollow87** [comment]
Sb0t does not support RCON.  RCON is mostly for game servers.

If you are asking if an external program can login to sb0t with a password answer would be no.

A custom sb0t script along with a custom Ares chat client you could implement that.
