### ISSUE TITLE
Release of Sb0t 5.41

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#28]
Hello hollow,

how can I give you my release?:

https://github.com/Nemo2478/sb0t-1/releases

Thanks

**Comment by hollow87** [comment]
Please use a pull request.  Your fork's code does not show any commits made by you.

**Comment by Nemo2478** [comment]
And how the linux can I make commits???

**Comment by hollow87** [comment]
sb0t linux is currently not being maintained.  I do not see myself in the foreseeable future working on it again.  I do not recommend using it.
