### ISSUE TITLE
Dont show in the room commands

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#31]
Hello hollow,

I wanted to make new commands. But I want that they are'nt showed in the room by all the users. 

And my question is: only the admins can this at commands with a substring transfer?

Thanks

**Comment by hollow87** [comment]
Sorry that English of yours is hard to understand but I will do my best.
`onCommand` event is triggered with a `#` or a `/` as first character in a line
`onHelp` event is triggered when a user types `/help` or `#help`

Checking the admin level in `onHelp` before displaying the command would allow you to only allow certain admin groups to see the commands same with `onCommand` if you check the admin level then you can make sure the user has the proper privileges

**Comment by Nemo2478** [comment]
Ok hollow,

thanks and sorry for my english please.....
