### ISSUE TITLE
Commmand #ping in Sb0t

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#33]
Hello hollow,

At the previus version of Sb0t (Sb0t 4.xx) there was the command /ping <id>.

Why this is not in the actually version of Sb0t ( Sb0t 5.xx)?

Bye and thanks

**Comment by hollow87** [comment]
Original developer I guess found no need for it when his 3rd party client does it with sb0t automatically.

**Comment by Nemo2478** [comment]
And what do you thing?
Would it be useful for Sb0t to make this command again?

I wanted to make a command like /setping <amount> to set a ping amount in the server so when a player go beyond the limit it will be kicked.

Do you thing its useful?

Bye and Thanks

**Comment by Nemo2478** [comment]
Ok,

so programme the command /setping hollow87 please :)

Bye and thanks

**Comment by hollow87** [comment]
There is no current implementation of clients to fully support this feature nor can I really see an need exactly for this.  While in theory a slowloris style attack is possible relying on a ping feature is not a proper way to mitigate it.  The pros do not outweigh the cons for this feature in my opinion thus this feature will not be implemented at this time.  I will close this issue.
