### ISSUE TITLE
Bug with Javascript (Registry)

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#34]
Hello,

the following code does'nt work:

var value = Registry.getValue("owner");
print(value);

Can the property getValue be fixed?

Bye and thanks!!

**Comment by hollow87** [comment]
You must set a value first before you can get it.

**Comment by Nemo2478** [comment]
Hello hellow87,

but I meaned to get the value that was set by Sb0t. I wanted to get the password from Sb0t. Is this possible?

Bye and thanks

**Comment by hollow87** [comment]
No. The scripts are sandboxed from each other

**Comment by Nemo2478** [comment]
Ok, 

thanks. It was not a bug, it was a mistake.

(Close please)
