### ISSUE TITLE
Property User.owner

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#35]
Hello,

this code does'nt work:

function onHelp(userobj) 
{
   	userobj.owner = true;
}

Are this property not working??

Bye and thanks

**Comment by hollow87** [comment]
That is because as the documentation says that property is read only

**Comment by Nemo2478** [comment]
Ohh sorry,

next time I must to read the type. I readed onlythe description.


Sorry

(Close please) :)
