### ISSUE TITLE
avatar rounded

### ISSUE THREAD

**Issue by danlins69** [AresChat/sb0t#37]
Friend, you could leave the avatar rounded?

**Comment by hollow87** [comment]
I think the avatars being rounded is handled client side.  I have not verified.

**Comment by hollow87** [comment]
The rounded avatars are handled client side, the server sends them as a full rectangle.

https://github.com/AresChat/cb0t/blob/7a3a0c919ca10c73e4249bc58228150f5b9821d7/cb0t/Misc/Avatar.cs#L38
