### ISSUE TITLE
ddos attacks

### ISSUE THREAD

**Issue by ddosprotect** [AresChat/sb0t#40]
thank you

**Comment by ddosprotect** [comment]
This overuse no longer reaches 100%, but remains at 50%. Sufficient use to slow down real connections ...

**Comment by hollow87** [comment]
Is there any way you can get me a memory dump during this?  (Note the memory dump would contain the server's owner password so don't do it from a production server.)

**Comment by ddosprotect** [comment]
small, full or kernel only ??

**Comment by ddosprotect** [comment]
give me your skype, or social network where you can pass ...

**Comment by ddosprotect** [comment]
tell me also how much I put in the paging file for the dump. I currently have 2047 ram. I leave it set by the system or put a concrete?

leave me a note of how to facilitate the data as best as possible!!!

**Comment by hollow87** [comment]
To create the dump file just right click the process in task manager details tab, and click create dump file

To send to me I have a PGP key ID of 0923FDF3 on hkp://keys.gnupg.net if you want to get https://www.gpg4win.org/download.html assuming you use windows.  
It is a bit buggy though.  You can encrypt the file with my public key and then I will be the only one able to decrypt it.

**Comment by ddosprotect** [comment]
leave the ticket open, do not close it I'm waiting for it to happen again to pass it on

**Comment by hollow87** [comment]
Thank you, I'll leave it open

**Comment by ddosprotect** [comment]
I already have the dump files. I made several of the same server at different time

**Comment by ddosprotect** [comment]
In 2 hours you get them

**Comment by hollow87** [comment]
Ok thanks, let me know and if you wish to encrypt them you can use my public pgp key with ID 0923FDF3 on hkp://keys.gnupg.net

**Comment by ddosprotect** [comment]
I'll pass you by mediafire.com the direct link to the download. download and decompress it. is in .zip format. Delete this message as soon as you download the drumpsmemorys, please. I trust you.
it is loading, as soon as I finish you pass links

**Comment by hollow87** [comment]
I can delete the message but anyone who is subscribed to this repository would also get an email so they choose of the message

**Comment by ddosprotect** [comment]
when you have downloaded you notify me to delete it from the cloud. it will also change it's server password.

**Comment by ddosprotect** [comment]
link: http://www.mediafire.com/file/p2o54zz666iummf/dumvolcatememory.zip
Size: 581 Mb
note: remember they are up to 5 drumps memory.

**Comment by ddosprotect** [comment]
when you download it, let me know to remove the file

**Comment by ddosprotect** [comment]
links of screens of excessive use of CPU
1: https://postimg.org/image/ng2m25nad/
2: https://postimg.org/image/51s2y6azp/
3: https://postimg.org/image/4dj8f8c9x/
4: https://postimg.org/image/7lnps9yjp/ [error closing sb0t, leaves it frizzed]
configuration server sb0t 5: https://postimg.org/image/miw6tabs5/

NOTE: do not consider the version of 5.38 (the same happened with 5.39)

**Comment by ddosprotect** [comment]
Things to keep in mind:
1: Note that only the ib0t enable tab is enabled
2: once it is attacked, if it gives stop to the server it leaves the error and touches abrir it again
3: I have 2 other sb0t open in the vps. the one that is blocked has the name of the drumpsmemory. (the 1,2,3 was so they would not replicate)
4: port: 54323

**Comment by hollow87** [comment]
I got the dump files and removed the url from this issue

**Comment by ddosprotect** [comment]
Okay, if you need anything else let me know.
I hope you can interpret it well, here I leave you more data
o.s: windows server 2012 r2
remember that it had 3 sb0t running at the same time with different ports. (the one that left off was 54323)
I only have the tcp protocol enabled
(the serverlog.txt file could not be accessed either "unable to open it while the attack lasted")

**Comment by hollow87** [comment]
Can you please provide the SOS.dll and and mscordacwks.dll located at C:\windows\Microsoft.NET\Framework64\v4.0.30319\

**Comment by ddosprotect** [comment]
also you should know that if you allow entry to the ib0t users room, but sde the ares or cb0t was off (10057)
link1: http://www.mediafire.com/file/o7dpu1h0lwaps2g
link2: http://download1075.mediafire.com/ggniy2nfm8yg/o7dpu1h0lwaps2g/frameworkddos.zip
size: 1.05 Mb

**Comment by ddosprotect** [comment]
it is worth mentioning that it is voxility, 900 Gb anti ddos. Never dropped the vps server. They only frizzed the sb0t5.
it did not have even higher peaks since they were in permanent mode and no sensor mode

**Comment by ddosprotect** [comment]
version net framework installed: 4.6
the same thing happens with 4.5

**Comment by ddosprotect** [comment]
When you have a test version, if you like the test, "test" you can send me to this email: themagazine2012@hotmail.com
do not forget to notify here for anything, please.

**Comment by ddosprotect** [comment]
could you download them?

**Comment by hollow87** [comment]
Sorry I sent that message right before I went to bed for the night I'll get those dll files I requested in a little bit.  They are not sensitive however they are needed as we have different framework versions as such I cant debug those dmp files without them.

**Comment by ddosprotect** [comment]
Okay, there I leave the files you asked for. if you need anything else let me know.
but the download works also let me know and upload them again

**Comment by hollow87** [comment]
I got the files, I'll let you know more as I find out thank you

**Comment by ddosprotect** [comment]
of nothing, but it is a too big failure in the server
screenshot: https://s26.postimg.org/uy1qqadrd/Screenshot_20170924-181907.png
see what percentage is now ...

**Comment by ddosprotect** [comment]
more than 60 percent

**Comment by ddosprotect** [comment]
take your time, whatever it takes.
The important thing is that it can be solved.
I just wanted you to know about the bug, nothing more.
a greeting!! (Y)

**Comment by ddosprotect** [comment]
link: https://s26.postimg.org/gr36y49u1/IMG_20170925_120650292.jpg
The same happens with sb0t 4.64 but does not prevent them from entering. it does not freeze. and does not pass to 10%.
I might help you
