### ISSUE TITLE
insert a <iframe> on room.

### ISSUE THREAD

**Issue by adahox** [AresChat/sb0t#42]
Hey hollow, 
there's a way to insert a correct iframe on room?
everytime we do that with js script, it puts a empty box on room without content.

**Comment by hollow87** [comment]
iframe support depends on client.  As I feel that arbitrary custom html from server to client is a security issue please expect such to be removed from sb0t and cb0t in future

**Comment by Cobreti1** [comment]
adahox you add style an topic gif see cool

**Comment by adahox** [comment]
i actually need is an iframe.because i want insert an service. but as @hollow87  said, there's no way
