### ISSUE TITLE
SendHtml

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#44]
Hello hollow87,

why doesn't work send html to users?

From which version of Sb0t doesn't work it?

Bye and thanks

**Comment by hollow87** [comment]
sendHtml works in sb0t fine. The client may not like using it however.

**Comment by Nemo2478** [comment]
???

How? You are saying that I must to configurate Ares???

**Comment by hollow87** [comment]
Custom html was removed from cb0t due to security issues. I can not comment if it works with ares or not

**Comment by Nemo2478** [comment]
And from ib0t?? Was it removed??

**Comment by hollow87** [comment]
ib0t never had it as far as I can remember.
I know it works because it is up to the client to support it or not. Also before it was removed from cb0t it was working as well.

**Comment by Nemo2478** [comment]
Hello hollow87,

and why was older versions of cb0t removed? How can I try it now?
With Ares it doesn't work. It appears only an empty little window.....

**Comment by hollow87** [comment]
The oldest version of cb0t here supports custom html.  Again it is up to the client to implement the server just sends.

**Comment by Nemo2478** [comment]
Hello hollow87,

and why doesn't work sendHtml with Ares?

Bye and thanks
