### ISSUE TITLE
identify PM photos.

### ISSUE THREAD

**Issue by adahox** [AresChat/sb0t#47]
Hi hollow,

where can i identify when someone sends a picture on private message? there a lot of warning's about abusive pictures on pv and we want stop that.

**Comment by hollow87** [comment]
Currently there is no way to do so.  Will add in future version.

**Comment by adahox** [comment]
but do you have any idea how ares send this images? if the server does not know when user sends private image how could it be sendt? directly connection throw ares clients?

**Comment by hollow87** [comment]
Private messages are not sent between user and user bypassing the server. Private messages are sent to the server who then delivers them to the other use.

Here are the relevant lines for scribble images inside a PM 
https://github.com/AresChat/sb0t/blob/61c0e5e1d62eabaf4e5fb69666850a2629f02631/core/TCPProcessor.cs#L289-L297

**Comment by Nemo2478** [comment]
How want you to identify the user who send you pictures?

**Comment by hollow87** [comment]
My guess and the way I implemented it was detecting if a PM contains a scribble or not.
Also I changed the `onScribbleCheck` to indicate if a scribble was in a PM.
`onScribbleCheck` will fire before `onPMBefore`

**Comment by adahox** [comment]
can i get clone with this feature right now?

**Comment by hollow87** [comment]
Yes it's in commit dabd2bc
