### ISSUE TITLE
Name reservation protections

### ISSUE THREAD

**Issue by azureblade7** [AresChat/sb0t#51]
Given the ease of bouncing someone's connection and then hijacking a username I would like to suggest the ability to protect/reserve a username on a per room basis ofc. Cheers!

**Comment by hollow87** [comment]
This is a good idea, I will need time to brainstorm some ideas on how to help mitigate possible abuse.  

For example Alice joins room "Apple" and Bob joins the same room.  Bob notices that when Alice leaves he can rename him self to her name.  He then registers Alice's name for himself and Alice can not do anything about it in that room.

Maybe, if admins or hosts of the room have to approve name registration.

Any other thoughts?

**Comment by ohgoshdean** [comment]
Could it be worth looking into utilising blockchain for this?
