### ISSUE TITLE
change server name color

### ISSUE THREAD

**Issue by nwer07** [AresChat/sb0t#52]
hi hollow , theres a way to add some feature to change the color of the server name ?
i wander if the color of the level can change too ...

**Comment by hollow87** [comment]
Are you talking about the admin colors you see in your client? 
In cb0t they would be

0) Black
1) Blue
2) Green
3) Red

**Comment by nwer07** [comment]
yeah the admin colors and the server color look this example [https://i.imgur.com/psGxmS5.jpg](url)

**Comment by hollow87** [comment]
Those colors are determined by the client.  
The server only tells the client what level as number (0-255)
The client decides how to display said number to the user.

**Comment by nwer07** [comment]
so how you can implement it ?

**Comment by hollow87** [comment]
It would have to be implemented on client side

**Comment by nwer07** [comment]
sorry, i think i explained wrong i mean the color of the sb0t servername in the userlist by default its red... but i see a different  server called runya it looks like orange i only use ares client

**Comment by hollow87** [comment]
That client is it ares or cb0t that it looks orange in?

**Comment by nwer07** [comment]
is ares client look [https://i.imgur.com/yFaZVR1.jpg](https://i.imgur.com/yFaZVR1.jpg)

**Comment by hollow87** [comment]
Ok, I will investigate all of ares color codes for the userlist when able.
Unless someone has the list of colors ares sets for what byte values.
