### ISSUE TITLE
connect with socket method - nodejs

### ISSUE THREAD

**Issue by adahox** [AresChat/sb0t#53]
hi hollow, 

i'm trying connect on my room by my own client web but for some reason, when i send the data to server, the server does not return anything. did u implemented some default response if connection fails?

**Comment by hollow87** [comment]
Are you talking about http or websocket?

**Comment by adahox** [comment]
Web socket with nodejs. i'm sending all login data to local server but for some reason in server log always get:
`03/11/2017 18:58:37 ping timeout or login timeout from 192.168.0.10 id: 0`

**Comment by hollow87** [comment]
Are you not sending any data when you connect? Also please provide a link
to your client when it is completed.

**Comment by adahox** [comment]
ya.
im sending some data like cb0t, i think. 
look : https://github.com/adahox/nodejs-ares-client

I know that javascript does not have data typing. but I've created a "similar" structure to the cb0t just to keep order for now.

**Comment by hollow87** [comment]
Please look at the data you are sending with a packet sniffer like wireshark or output to a file as well. And compare it to the one a regular client sends
