### ISSUE TITLE
unmask ip ib0t

### ISSUE THREAD

**Issue by nwer07** [AresChat/sb0t#55]
hey hollow, could you add a command to unmask the ip ib0t always enter very annoying users pretending be  other people, at least know who they are

**Comment by hollow87** [comment]
The first 2 octets are not masked and can always use the version property as that contains user agent then there is also the guid

**Comment by nwer07** [comment]
the user guid is different when i ban a user from ares he can still using ib0t or theres a ip encode in the version property?

**Comment by hollow87** [comment]
The first 2 octets of the ip should match if they are same person and not using a proxy.

**Comment by nwer07** [comment]
yeah but the first 2 octets match too with other user who are using the same internet company  :(
