### ISSUE TITLE
A seemingly unbanable user

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#56]
Hello,

these last days are a user that are disturbing in the room. I tried to ban her but there is an error. The error says that I can't ban a user who has a higher level than mine. I checked the level of this user but it was 0. Is there a bug or why he can be unbanable?

Thanks

**Comment by hollow87** [comment]
Are you the host of the room? Can you provide more information like what your level was, the other persons level etc.

**Comment by Nemo2478** [comment]
Ohh yes, of course. 
I am the owner of the room. My level was 3 or the highest. The other persons level was 0 or nothing. But nevertheless the error came that i can't ban a user who has a higher level than mine, although that was not the case.

Thanks

**Comment by Nemo2478** [comment]
I want to add in that I see an another user in my room that are "unbanable" too.
When I ban her, he is disconnected from the room. But in a few seconds, he are again in my room; with the same nick and the same and the same IP. I'm tired of banning him.
What's happening in Sb0t? Poop

Thanks for reading

**Comment by hollow87** [comment]
Is your room linked?

**Comment by Nemo2478** [comment]
No.

**Comment by stuart2** [comment]
Believe this is an edge case scenario, this is the only report of this happening and never seen it happen before. 

If this becomes a repeatable issue please open a new issue and we will look into it further.
