### ISSUE TITLE
Cloak doen't work in JavaScript with ib0t

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#59]
Hello,

why doesn't work to cloak an user trough JavaScript, if the user, who I want to cloak use ib0t?

Bye and thanks

**Comment by hollow87** [comment]
Looks like it doesn't work because it never was made to work with ib0t

https://github.com/AresChat/sb0t/blob/master/core/ib0t/ib0tClient.cs#L330-L334
```csharp
 public bool Cloaked
 {
     get { return false; }
     set { }
}
```
