### ISSUE TITLE
From where know Sb0t my ip?

### ISSUE THREAD

**Issue by Nemo2478** [AresChat/sb0t#6]
Hello,

at first I must to say what I did:

I created a bot to connect to Sb0t. I connected to a Sb0t server two times.
The first time I sended the MSG_CHAT_CLIENT_LOGIN - Packet

The second time I did not send it. But Sb0t knew who I am. Why? I had not send the MSG_CHAT_CLIENT_LOGIN - Packet which contains my IP. 

From where know Sb0t my ip?

Thanks :)

**Comment by thispixel** [comment]
sb0t could of seen it as a reconnection

**Comment by ctrlshift75** [comment]
It is bad practice to trust a client to provide correct information in the application layer including IP address. Sb0t does get the IP in an alternative way.
