### ISSUE TITLE
Arca Eclipse

### ISSUE THREAD

**Issue by dev45** [AresChat/sb0t#63]
Hi friend, it's me again! I know that here is not the right place to ask this question, but since you changed to read only the project Arca4 had no other place; Anyway, I wanted to know if you have the source code of the Arca Eclipse 3.3 and if you could pass it to me Friend? Of course it's not too much trouble!

And another question that arc4 source works to develop a new server?

**Comment by hollow87** [comment]
You are right wrong place.
