### ISSUE TITLE
Style Template.htm

### ISSUE THREAD

**Issue by dev45** [AresChat/sb0t#65]
Hi Hollow! How Are You My Friend?
I would like to know how you can place an image with a gif extension as a chat background and that from the sensation that it was a rain of ess image something like this [Link to Example](https://silversurferdeveloper.blogspot.com/2020/04/test.html)

could you help me friend?
I hope you can respond soon!! Thanks!!
Best Regards!!!

**Comment by stuart2** [comment]
You cannot use gif's currently.
