### ISSUE TITLE
Viewing Youtube Videos On Chatroom

### ISSUE THREAD

**Issue by dev45** [AresChat/sb0t#66]
**Hi Hollow!! How Are You My Friend??**
**Sorry, I would like to know how to make a script to watch YouTube videos in the room; Rather, they reproduce in the room by placing the link in the room. - Could you give me a hand if it is possible, friend?**

**Could You Help Me With That Bro?**

**Best Regards!!**

**Comment by stuart2** [comment]
This isn't possible, sorry.
