### ISSUE TITLE
sb0t 5 Template for Visual Studio

### ISSUE THREAD

**Issue by GioUniderp** [AresChat/sb0t#67]
I would like to get the template for building extension for sb0t5. Is there a download link? Or some tutorial on how to do without extension? Thank you!

**Comment by GioUniderp** [comment]
I tried to get here https://archive.codeplex.com/?p=sb0t5 but without success.

**Comment by stuart2** [comment]
Hello,

It is likely this feature is going to be deprecated in the future if you still would like to use this feature, then I will make a draft plugin for you.

**Comment by GioUniderp** [comment]
Yes, I would like to be very grateful if I can do it!

**Comment by GioUniderp** [comment]
I want to, I am grateful if I can do it

**Comment by wendelalves93** [comment]
[Link !!](https://github.com/wendelalves93/Sb0t5-Template)
