### ISSUE TITLE
servers.dat need update (this for users who ask this a lot to me)

### ISSUE THREAD

**Issue by lexicon06** [AresChat/sb0t#69]
Room won't display on Ares unless you copy ChatroomIPs.dat from ares and put into sb0t folder as servers.dat
[servers.zip](https://github.com/AresChat/sb0t/files/7790831/servers.zip)

**Comment by stuart2** [comment]
None of the ips in your servers.dat are actually valid. Would need to put a room up permanently to try rebuild the list.
