### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by thispixel** [AresChat/sb0t#8]
With people sharing what _could_ be malicious binaries, I think it is the right time to place sb0t and cb0t under opensource licencing, forcing people who do want to ship their own version to include the sourcecode also.

Is anyone against this?

**Comment by thispixel** [comment]
@hollow87 @ctrlshift75

**Comment by ctrlshift75** [comment]
I'm for this. GPL v2?

**Comment by thispixel** [comment]
Any reason as to not V3?

**Comment by thispixel** [comment]
Yes v2 should be good enough

**Comment by ctrlshift75** [comment]
Can't really think of why not v3, but do we want the code to have to be provided even if it's not distributed? If so maybe AGPLv3

**Comment by thispixel** [comment]
yeah v3 is not very clear on that v2 is, i'll take a look at APGL

**Comment by ctrlshift75** [comment]
I think it's other way around GPLv3 states that network operators do not need to share source if clients do not receive the binary

**Comment by thispixel** [comment]
I have added APGL v3
