### ISSUE TITLE
it is possible to develop the Join Filter:redirect for ib0t and the /redirect command ?

### ISSUE THREAD

**Issue by ManuD33P** [AresChat/sb0t#81]
**This is how you do it in ares,**

  ```
public void Redirect(String hashlink)
        {
            Room room = Hashlink.DecodeHashlink(hashlink);

            if (room != null && this.Level == ILevel.Regular)
            {
                byte[] buf;

                while (this.data_out.Count > 0)
                    if (!this.data_out.TryDequeue(out buf))
                        break;

                this.SendPacket(TCPOutbound.Redirect(this, room));
                this.Disconnect();
            }
        }
        
```
        
     *But in ib0t it is not developed*
     `
     public void Redirect(String hashlink) { }        
      `
      The idea is that there is a standard package for ib0ts and mobile clients. there are already mobile clients haha.
      
*# Reference Link*
[ib0t Client](https://github.com/bsjaramillo/sb0t/blob/32425ecc187127af738ccb30b1544e35a7370eac/core/ib0t/ib0tClient.cs#LL352C1-L353C1)

[Ares Client](https://github.com/AresChat/sb0t/blob/b8923f20eeb92f29912dc9641ad030a03cb1901d/core/AresClient.cs#L299)

**Comment by bsjaramillo** [comment]
not, its not possible, now, close this issue.

**Comment by bsjaramillo** [comment]
It was resolved at [sb0t for inbizio clients](https://github.com/bsjaramillo/sb0t/blob/master/core/ib0t/ib0tClient.cs#L352), now, close this issue xd
